services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\RoadRunner\EventListener\SessionListener:
        arguments:
            $sessionStorageOptions: '%session.storage.options%'

    App\RoadRunner\EventListener\CleanerListener: ~
