easy_admin:
    entities:
        Review:
            class: App\Review\Entity\Review
            controller: App\Review\Controller\ReviewController
            disabled_actions: ['show', 'edit', 'delete']
            list:
                fields:
                    - { property: 'author', label: 'Автор' }
                    - { property: 'manufacturer', label: 'Производитель автомобиля' }
                    - { property: 'model', label: 'Модель автомобиля' }
                    - { property: 'content', label: 'Отзыв' }
                    - { property: 'source', label: 'Источник' }
                    - { property: 'publishAt', label: 'Когда обудликова' }
            form:
                fields:
                    - { property: 'author', label: 'Автор' }
                    - { property: 'manufacturer', label: 'Производитель автомобиля' }
                    - { property: 'model', label: 'Модель автомобиля' }
                    - { property: 'content', label: 'Отзыв' }
                    - { property: 'source', label: 'Источник' }
                    - { property: 'publishAt', label: 'Опубликована', type: 'date_immutable', type_options: { input: 'datetime_immutable' } }
            new:
                title: 'Создать новый Отзыв'
                form_options: { data_class: App\Review\Form\ReviewDto }
            edit:
                title: 'Редактировать Отзыв'

doctrine_mongodb:
    document_managers:
        www:
            mappings:
                review:
                    type: annotation
                    prefix: App\Review\Document
                    dir: "%kernel.project_dir%/src/Review/Document"
