doctrine:
    dbal:
        types:
            phone_number: \Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
        default_connection: default
        connections:
            default:
                mapping_types:
                    enum: string
                charset:  UTF8
                server_version: mariadb-10.3.10
                wrapper_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Connection'
                driver_class: 'Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Driver\PDOMySql\Driver'
                options:
                    x_reconnect_attempts: 3
                host:     "%env(MYSQL_HOST)%"
                port:     "%env(int:MYSQL_PORT)%"
                dbname:   "%env(MYSQL_NAME)%"
                user:     "%env(MYSQL_USER)%"
                password: "%env(MYSQL_PASSWORD)%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: App\Doctrine\ORM\Mapping\NamespaceNamingStrategy
        auto_mapping: false
        mappings:
            App:
                type: annotation
                prefix: App\Entity
                dir: '%kernel.project_dir%/src/Entity'
                is_bundle: false
            moneyphp:
                type: yml
                prefix: Money
                dir: '%kernel.project_dir%/config/orm/money'
                is_bundle: false

parameters:
    env(MYSQL_HOST): mysql
    env(MYSQL_PORT): 3306
    env(MYSQL_USER): db
    env(MYSQL_NAME): db
    env(MYSQL_PASSWORD): '%env(file:MYSQL_PASSWORD_FILE)%'
    env(MYSQL_PASSWORD_FILE): /run/secrets/mysql_password

services:
    Doctrine\ORM\Mapping\NamingStrategy:
        alias: App\Doctrine\ORM\Mapping\NamespaceNamingStrategy
