doctrine_mongodb:
    auto_generate_proxy_classes: !php/const Doctrine\ODM\MongoDB\Configuration::AUTOGENERATE_FILE_NOT_EXISTS
    auto_generate_persistent_collection_classes: !php/const Doctrine\ODM\MongoDB\Configuration::AUTOGENERATE_FILE_NOT_EXISTS
    auto_generate_hydrator_classes: !php/const Doctrine\ODM\MongoDB\Configuration::AUTOGENERATE_FILE_NOT_EXISTS
    connections:
        www:
            server: mongodb://mongo:27017
            options: {}
    default_database: www
    document_managers:
        www:
            connection: www
            database: www
