doctrine:
    dbal:
        types:
            phone_number: \Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
            uuid:  Ramsey\Uuid\Doctrine\UuidType
        connections:
            default:
                charset:  UTF8
                server_version: 12.2
                driver:   pdo_pgsql
                host:     db
                port:     5432
                dbname:   db
                user:     db
                password: "%env(DATABASE_PASSWORD)%"
                schema_filter: ~^(?!.*_view$).*~

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: App\Shared\Doctrine\ORM\Mapping\NamespaceNamingStrategy
                auto_mapping: false
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.metadata_cache.pool
                mappings:
                    cron:
                        type: annotation
                        prefix: Cron\CronBundle\Entity
                        dir: '%kernel.project_dir%/vendor/cron/cron-bundle/Entity'
                        is_bundle: false
                    moneyphp:
                        type: xml
                        prefix: Money
                        dir: '%kernel.project_dir%/config/orm/money'
                        is_bundle: false

doctrine_migrations:
    migrations_paths:
        'App\Migrations': 'src/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 1024
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'

framework:
    cache:
        pools:
            doctrine.metadata_cache.pool:
                adapter: cache.adapter.array

parameters:
    env(DATABASE_PASSWORD): '%env(default:default_db_password:trim:file:DATABASE_PASSWORD_FILE)%'
    env(DATABASE_PASSWORD_FILE): /run/secrets/database_password
    default_db_password: db

services:
    Doctrine\ORM\Mapping\NamingStrategy:
        alias: App\Shared\Doctrine\ORM\Mapping\NamespaceNamingStrategy
