framework:
    #esi:             ~
    secret:          "%env(APP_SECRET)%"
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
        auto_mapping: [null]
    serializer:
        enable_annotations: true
    trusted_hosts:   ~
    session:
        handler_id: session.handler.memcached
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: '%kernel.debug%'
    cache:
        pools:
            app.cache.tenant_relations:
                adapter: cache.adapter.apcu
                public: false

services:
    Symfony\Component\PropertyAccess\PropertyAccessorInterface:
        alias: property_accessor

    Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface:
        alias: argument_resolver

    session.memcached:
        class: Memcached
        public: true
        calls:
            - [ addServer, [ '%env(SESSION_MEMCACHED_HOST)%', '%env(SESSION_MEMCACHED_PORT)%' ]]
    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: [ '@session.memcached' ]

parameters:
    env(SESSION_MEMCACHED_HOST): 'memcached'
    env(SESSION_MEMCACHED_PORT): '11211'
