security:
    encoders:
        App\User\Entity\User: auto

    providers:
        user_provider:
            entity:
                class: App\User\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        callback:
            pattern: ^/callback
            guard:
                authenticators:
                    - App\Sms\Security\CallbackGuard
            stateless: true

        graphql_www:
            pattern: ^/api/www
            stateless: true
            anonymous: true

        admin:
            anonymous: ~
            logout:
                path: logout
#                delete_cookies:
#                    PHPSESSID: ~
            form_login:
                provider: user_provider
                csrf_token_generator: security.csrf.token_manager
                check_path: login_check
                login_path: login

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/r/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/www, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
