security:
    encoders:
        App\User\Entity\User: auto

    providers:
        user_provider:
            entity:
                class: App\User\Entity\User
                property: username
                manager_name: landlord

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            anonymous: ~
            logout:
                path: admin_logout
                delete_cookies:
                    PHPSESSID: ~
            form_login:
                provider: user_provider
                csrf_token_generator: security.csrf.token_manager
                check_path: admin_login_check
                login_path: admin_login

        api:
            pattern: ^/api/jsonrpc$
            stateless: true
            anonymous: true

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/jsonrpc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_EMPLOYEE }

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN

        ROLE_ADMIN:
            - ROLE_EMPLOYEE
            - ROLE_MAINTENANCE_CONFIGURATOR
            - ROLE_CUSTOMER_FEEDBACK
            - ROLE_USER_MANAGER
            - ROLE_EMPLOYEE_MANAGER
            - ROLE_DICTIONARY
            - ROLE_ACCOUNTING
            - ROLE_CUSTOMER
            - ROLE_REPORT
            - ROLE_ORDER
            - ROLE_STOCK

        ROLE_CUSTOMER_FEEDBACK:
            - ROLE_WWW_SECTION
