twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        - '%kernel.project_dir%/templates'
    exception_controller: App\Controller\ExceptionController::showAction
    globals:
        state: '@App\State'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'easy_admin/form.html.twig'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\TextExtension: ~
    Twig\Extension\StringLoaderExtension: ~
