version: '3.7'

services:
    app:
        image: automagistre/app@sha256:2c76a491b73dcb229ee1d0a96fa8dfd9ef937cc26ef7ad0688fa3046c1d8a498
        labels:
            ru.grachevko.dhu: '{sto,www}.automagistre.local'
            restartable: 'true'
        networks:
            default:
                aliases:
                    - php-fpm
        volumes:
            - ./:/usr/local/app
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            MYSQL_PASSWORD: 'db'

    landlord: &mysql
        image: mariadb:10.3.10
        labels:
            ru.grachevko.dhu: 'landlord.automagistre.local'
        volumes:
            -
                type: tmpfs
                target: /var/lib/mysql
                tmpfs:
                    size: 1024m
            - ./:/usr/local/app
        environment:
            MYSQL_DATABASE: landlord
            MYSQL_USER: db
            MYSQL_PASSWORD: db
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        healthcheck:
            test: CMD echo "SELECT 1" | mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s

    tenant_msk:
        <<: *mysql
        labels:
            ru.grachevko.dhu: 'tenant_msk.automagistre.local'
        environment:
            MYSQL_DATABASE: tenant
            MYSQL_USER: db
            MYSQL_PASSWORD: db
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

    tenant_kazan:
        <<: *mysql
        labels:
            ru.grachevko.dhu: 'tenant_kazan.automagistre.local'
        environment:
            MYSQL_DATABASE: tenant
            MYSQL_USER: db
            MYSQL_PASSWORD: db
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

    memcached:
        image: memcached:1.5.11-alpine
        labels:
            ru.grachevko.dhu: 'memcached.automagistre.local'
            restartable: 'false'
        healthcheck:
            test: nc -z 127.0.0.1 11211
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 5s

    dockerhost:
        image: qoomon/docker-host:2.0.4
        cap_add:
            - NET_ADMIN
            - NET_RAW
