version: '3.7'

services:
    app:
        image: automagistre/app@sha256:3e3153d32126c9dfa25900e230e183d7877dc644c1ed2b072ffdedb1c276081b
        command: rr serve
        labels:
            ru.grachevko.dhu: '{sto,www}.automagistre.local'
            restartable: 'true'
        volumes:
            - ./:/usr/local/app
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DATABASE_PASSWORD: db

    mysql:
        image: mariadb:10.3.10
        labels:
            ru.grachevko.dhu: 'mysql.automagistre.local'
        volumes:
            -
                type: tmpfs
                target: /var/lib/mysql
                tmpfs:
                    size: 1024m
            - ./:/usr/local/app
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: db
            MYSQL_PASSWORD: db
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        healthcheck:
            test: CMD echo "SELECT 1" | mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s

    memcached:
        image: memcached:1.5.11-alpine
        labels:
            ru.grachevko.dhu: 'memcached.automagistre.local'
            restartable: 'false'
        healthcheck:
            test: nc -z 127.0.0.1 11211
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 5s

    dockerhost:
        image: qoomon/docker-host:2.0.4
        cap_add:
            - NET_ADMIN
            - NET_RAW
