_security:
    resource: '../src/Controller/Admin/SecurityController.php'
    type: annotation

_part_explorer:
    resource: '../src/Controller/Admin/PartExplorerController.php'
    type: annotation

logout:
    path: /logout

login_check:
    path: /login
    methods: [ 'POST' ]
