_security:
    resource: '../src/Controller/Admin/SecurityController.php'
    type: annotation

_home:
    resource: '../src/Controller/Admin/HomeController.php'
    type: annotation

_part_explorer:
    resource: '../src/Controller/Admin/PartExplorerController.php'
    type: annotation
    prefix: /{tenant}

_report:
    resource: '../src/Controller/Admin/ReportController.php'
    type: annotation
    prefix: /{tenant}

logout:
    path: /logout

login_check:
    path: /login
    methods: [ 'POST' ]
