version: '3.7'

services:
    app:
        image: automagistre/app:dev
        hostname: automagistre.local
        labels:
            subdomains: sto www
            restartable: 'true'
        volumes:
            - ../:/usr/local/app
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            XDEBUG: 'false'
            OPCACHE: 'true'
            MIGRATIONS: 'false'

    mysql:
        image: mariadb:10.1.23
        hostname: mysql.automagistre.local
        volumes:
            - mysql-db:/var/lib/mysql
            - ../:/usr/local/app
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: db
            MYSQL_PASSWORD: db
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

    memcached:
        image: memcached:1.5.4-alpine
        labels:
            restartable: 'false'

volumes:
    mysql-db:
        driver: local
        driver_opts:
            device: tmpfs
            type: tmpfs
            o: size=1024m
