services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Shared\ArgumentResolver\ArgumentResolver:
        arguments:
            $argumentValueResolvers: !tagged_iterator
                tag: 'app.argument_value_resolver'
                index_by: 'priority'

    App\Shared\ArgumentResolver\ArgumentResolverInterface: '@App\Shared\ArgumentResolver\ArgumentResolver'
