easy_admin:
    entities:
        Part:
            class: App\Part\Domain\Part
            controller: App\Part\Ports\EasyAdmin\PartController
            disabled_actions: ['delete']
            label: 'Запчасти'
            templates:
                show: 'easy_admin/part/show.html.twig'
            show:
                title: 'Запчасть № {{ entity.id }}'
                fields:
                    - { property: 'name', label: 'Название' }
                    - { property: 'manufacturer.name', label: 'Производитель' }
                    - { property: 'number', label: 'Номер', template: 'easy_admin/field_part_number.html.twig' }
                    - { property: 'price', label: 'Цена', template: 'easy_admin/field_money.html.twig' }
                    - { property: 'discount', label: 'Скидка', template: 'easy_admin/field_money.html.twig' }
                    - { property: 'universal', label: 'Универсальная' }
            list:
                title: 'Запчасти'
                fields:
                    - { property: 'name', label: 'Название', template: 'easy_admin/field_part.html.twig', item: true, stock: true, referer: false }
                    - { property: 'manufacturer.name', label: 'Производитель' }
                    - { property: 'number', label: 'Номер', template: 'easy_admin/field_part_number.html.twig' }
                    - { property: 'price', label: 'Цена', template: 'easy_admin/field_money.html.twig' }
                    - { property: 'discount', label: 'Скидка', template: 'easy_admin/field_money.html.twig' }
                    - { property: 'universal', label: 'Универсальная', template: 'easy_admin/default/field_boolean.html.twig' }
            form:
                fields:
                    - { property: 'manufacturer', label: 'Производитель', type_options: { required: true, placeholder: 'Пусто' } }
                    - { property: 'number', label: 'Номер' }
                    - { property: 'name', label: 'Название' }
                    - { property: 'price', label: 'Цена', type: App\Form\Type\MoneyType }
                    - { property: 'discount', label: 'Скидка', type: App\Form\Type\MoneyType }
                    - { property: 'universal', label: 'Универсальная' }
            new:
                title: 'Создать новую запчасть'
                form_options: { data_class: \App\Part\Form\Part }
            edit:
                title: 'Редактировать запчасть'
                fields:
                    - { property: 'manufacturer', label: 'Производитель', type_options: { disabled: true } }
                    - { property: 'number', label: 'Номер', type_options: { disabled: true } }
        PartCase:
            class: App\Part\Domain\PartCase
            controller: App\Part\Ports\EasyAdmin\PartCaseController
            disabled_actions: ['show', 'edit', 'search', 'list']
            new:
                title: 'Создать применения запчасти к кузову'
                fields:
                    - { property: 'part', label: 'Запчасть', type: 'easyadmin_autocomplete', type_options: { disabled: true } }
                    -   property: 'carModel'
                        label: 'Модель'
                        type: 'easyadmin_autocomplete'
                        help: 'Проивзодитель, Модель, Год, Поколение, Комплектация, Лошадинные силы'

doctrine:
    orm:
        entity_managers:
            landlord:
                mappings:
                    part:
                        type: annotation
                        prefix: App\Part\Domain
                        dir: '%kernel.project_dir%/src/Part/Domain'
