services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\JSONRPC\ApiEvaluator:
        arguments:
            - !tagged_locator { tag: 'jsonrpc.method', index_by: 'jsonrpc.method' }

    App\JSONRPC\CommandArgumentValueResolver:
        tags:
            - { name: app.argument_value_resolver, priority: -100 }

    App\JSONRPC\EndpointAction:
        tags:
            - { name: controller.service_arguments }
