doctrine:
    orm:
        entity_managers:
            landlord:
                metadata_cache_driver: apcu
                query_cache_driver: apcu
            #result_cache_driver: apcu
            tenant:
                metadata_cache_driver: apcu
                query_cache_driver: apcu
            #result_cache_driver: apcu
