monolog:
    handlers:
        main:
            type: stream
            path: 'php://stdout'
            level: info
            formatter: 'monolog.formatter.json'
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
