_admin:
    resource: './routes/admin.yaml'
    name_prefix: admin_

# MUST BE LAST
_easy_admin:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    type: annotation
    prefix: /{tenant}
