parameters:
    locale: ru

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
        bind:
            $debug: '%kernel.debug%'

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags:
                - { name: doctrine.event_subscriber }

        Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
            tags:
                - { name: controller.argument_value_resolver, priority: 50 }

    App\:
        resource: '../src'
        exclude: '../src/{Entity,Enum,Model}'
    App\Controller\:
        resource: '../src/Controller'
        tags:
            - { name: controller.service_arguments }

    Symfony\Bridge\Doctrine\Form\DoctrineOrmTypeGuesser:
        alias: easyadmin.form.guesser.missing_doctrine_orm_type_guesser

    App\Router\ListeningRouterDecorator:
        decorates: router

    App\Doctrine\DBAL\FixPostgreSQLDefaultSchemaListener:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }

    App\Mercure\JwtProvider:
        arguments:
            - '%env(MERCURE_JWT_KEY)%'
