parameters:
    locale: ru

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags:
                - { name: doctrine.event_subscriber }

        Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
            tags:
                - { name: controller.argument_value_resolver, priority: 50 }

        App\Shared\Identifier\IdentifierFormatterInterface:
            tags:
                - { name: identifier_formatter }

    App\:
        resource: '../src'
    App\Controller\:
        resource: '../src/Controller'
        tags:
            - { name: controller.service_arguments }

    Symfony\Bridge\Doctrine\Form\DoctrineOrmTypeGuesser:
        alias: easyadmin.form.guesser.missing_doctrine_orm_type_guesser
